---
# AMD64 Build
kind: pipeline
type: docker
name: operator_amd64

platform:
  arch: amd64
  os: linux

steps:
- name: publish_backend_container
  image: plugins/docker
  settings:
    debug: true
    mtu: 1000
    registry: harbor.0x01.host
    dockerfile: Dockerfile
    platform: linux/amd64
    repo: harbor.0x01.host/library/squest-operator
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest-linux-amd64
    
trigger:
  branch:
  - main

# ARM64 Build
---
kind: pipeline
type: docker
name: operator_arm64

platform:
  arch: arm64
  os: linux

steps:
- name: publish_backend_container
  image: plugins/docker
  settings:
    mtu: 1000
    debug: true
    registry: harbor.0x01.host
    dockerfile: Dockerfile
    platform: linux/arm64
    repo: harbor.0x01.host/library/squest-operator
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    tags:
      - latest-linux-arm64
    
trigger:
  branch:
  - main


---
kind: pipeline
type: docker
name: push_manifest

clone:
  disable: yes

steps:
- name: manifest
  image: plugins/manifest
  settings:
    registry: harbor.0x01.host
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    target: harbor.0x01.host/library/squest-operator:latest
    template: harbor.0x01.host/library/squest-operator:latest-OS-ARCH
    platforms:
      - linux/amd64
      - linux/arm64

trigger:
  branch:
  - main

depends_on:
  - operator_amd64
  - operator_arm64
