# permissions for end users to edit squests.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: squest-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: squest-operator
    app.kubernetes.io/part-of: squest-operator
    app.kubernetes.io/managed-by: kustomize
  name: squest-editor-role
rules:
- apiGroups:
  - web.hewlettpackard.com
  resources:
  - squests
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - web.hewlettpackard.com
  resources:
  - squests/status
  verbs:
  - get
