---
# tasks file for Squest

## Create Database secret
- name: Create a secrets for mariadb
  kubernetes.core.k8s:
    definition:
      kind: Secret
      apiVersion: v1
      metadata:
        namespace: '{{ ansible_operator_meta.namespace }}'
        name: '{{ ansible_operator_meta.name }}-mariadb-secret'
      data:
        root-password: "{{ db.root_password | b64encode }}"
        password: "{{ db.password | b64encode }}"

## Create Database Deployment

- name: Deploy Database
  kubernetes.core.k8s:
    state: present
    template:
      path: '/deployments/database.yaml.j2'
