apiVersion: v1
kind: Namespace
metadata:
  name: squest
---

apiVersion: web.hewlettpackard.com/v1alpha1
kind: Squest
metadata:
  labels:
    app.kubernetes.io/name: squest
    app.kubernetes.io/instance: squest-sample
    app.kubernetes.io/part-of: squest-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: squest-operator
  name: squest-sample
  namespace: squest
spec:
  db:
    persistence: 
      enabled: true
      storage_class: longhorn-main
    node_selector: |
      kuberentes.io/arch: amd64
    root_password: toor
    password: toor
    name: squest
    user: squest