# apiVersion: v1
# kind: Namespace
# metadata:
#   name: squest
# ---

apiVersion: web.hewlettpackard.com/v1alpha1
kind: Squest
metadata:
  labels:
    app.kubernetes.io/name: squest
    app.kubernetes.io/instance: squest-sample
    app.kubernetes.io/part-of: squest-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: squest-operator
  name: squest-sample
  namespace: squest
spec:
  redis:
    node_selector: |
      kubernetes.io/arch: amd64
    password: toor
  rabbitmq:
    persistence: 
      enabled: true
      storage_class: longhorn-main
      size: 2Gi
    node_selector: |
      kubernetes.io/arch: amd64
  db:
    persistence: 
      enabled: true
      storage_class: longhorn-main
      size: 2Gi
    node_selector: |
      kubernetes.io/arch: amd64
    root_password: toor
    password: toor
    user: squest
  squest:
    django:
      ingress:
        enabled: false
        host: "squest.0x01.host"
        class: traefik
      image: quay.io/hewlettpackardenterprise/squest:2.5.1
      node_selector: |
        kubernetes.io/arch: amd64
      persistence:
        enabled: true
        storage_class: longhorn-main
        size: 1Gi