# apiVersion: v1
# kind: Namespace
# metadata:
#   name: squest
# ---

apiVersion: web.hewlettpackard.com/v1alpha1
kind: Squest
metadata:
  labels:
    app.kubernetes.io/name: squest
    app.kubernetes.io/instance: squest
    app.kubernetes.io/part-of: squest-operator
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: squest-operator
  name: squest
  namespace: squest
spec:
  node_selector: ''
  redis_node_selector: ''
  rabbitmq_node_selector: ''
  db_node_selector: ''
  django_node_selector: |
    kubernetes.io/arch: amd64
  maintenance_node_selector: ''

  storage_class: default

  db_persistence_enabled: true
  db_persistence_storage: 2Gi
  db_user: squest
  db_password: toor
  db_root_password: toor

  rabbitmq_persistence_enabled: true
  rabbitmq_persistence_storage: 2Gi

  django_persistence_enabled: true
  django_persistence_storage: 1Gi
  django_ingress_enabled: false
  django_ingress_class: traefik
  django_ingress_hostname: squest.0x01.host
  django_image: quay.io/hewlettpackardenterprise/squest:2.5.1

  redis_password: toor
